footer:
  rails_link: https://www.railstutorial.org
  michale_link: https://www.michaelhartl.com/
  rails_news_link: https://news.railstutorial.org/

rails:
  help: https://www.railstutorial.org/help
  book: https://www.railstutorial.org/book
  contact: https://www.railstutorial.org/contact

learnenough:
  https://www.learnenough.com/

screencasts:
  https://screencasts.railstutorial.org/
